spring.application.name=store

spring.jpa.hibernate.ddl-auto=validate

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/room-booking
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/room-booking/protocol/openid-connect/certs