spring.jpa.hibernate.ddl-auto=validate

# The important architecture is that production will eventually start Spring using:
# SPRING_PROFILES_ACTIVE=prod
# and secrets/configuration will come from the deployment environment.