spring.datasource.url=jdbc:postgresql://localhost:5432/store_e2e
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate

spring.flyway.locations=classpath:db/migration,classpath:db/e2e

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/room-booking
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/room-booking/protocol/openid-connect/certs