apiVersion: v1
kind: Secret

metadata:
  name: postgres-secret

type: Opaque

stringData:
  POSTGRES_DB: room_booking
  POSTGRES_USER: room_booking
  POSTGRES_PASSWORD: local-k8s-password # a local learning password. Don't use a real password here.