CREATE TABLE bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    user_id BIGINT NOT NULL,
    room_id BIGINT NOT NULL,

    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,

    CONSTRAINT fk_booking_user FOREIGN KEY (user_id) REFERENCES users(id), -- This foreign key constraint ensures that each booking is associated with a valid user.
    CONSTRAINT fk_booking_room FOREIGN KEY (room_id) REFERENCES rooms(id), -- This foreign key constraint ensures that each booking is associated with a valid room.
    CONSTRAINT chk_booking_time CHECK (start_time < end_time) -- This check constraint ensures that the start time of a booking is always before the end time.
);

CREATE INDEX idx_bookings_room_time ON bookings(room_id, start_time, end_time); -- This index helps to quickly find bookings for a specific room within a time range.

-- A booking belongs to one user and one room.

-- The database relationship is:

--  users
--   id
--    ↑
--    │
-- bookings
--   user_id
--   room_id
--    │
--    ↓
--  rooms
--    id